### ISSUE TITLE
About the opanscan_val_gt

### ISSUE THREAD

**Issue by xulingjing88** [YoujunZhao/OpenScan#1]
Hello, 
**thank you very much for this fantastic work!** I really appreciate your efforts. I have a question regarding the opanscan_val_gt you provided. I'm not entirely sure about the specific attribute labels corresponding to each number. Could you please clarify how to interpret them? Or, if possible, could you provide a .txt file with the label mappings?

**Thank you in advance!**

**Comment by YoujunZhao** [comment]
Hi @xulingjing88 ,

We upload a label mapping file in [OneDrive](https://portland-my.sharepoint.com/:f:/g/personal/youjzhao2-c_my_cityu_edu_hk/EtTl_Lv8-idGtgjn-b1jpKUBulI_pQ1TonnV3Ypu8WUqYw?e=Tir9M7). In these files, each attribute label has a corresponding class number.

If you face any problems with the dataset, feel free to reach out to me.

Thanks

**Comment by xulingjing88** [comment]
Thank you so much! This is very helpful.
